
'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2, Newspaper, Sparkles } from 'lucide-react';
import { SidebarTrigger } from '@/components/ui/sidebar';
import { ThemeToggle } from '@/components/theme-toggle';
import { generateAiNews, GenerateAiNewsOutput } from '@/ai/flows/generate-ai-news';
import { useToast } from '@/hooks/use-toast';

export default function NewsPage() {
    const [news, setNews] = useState<GenerateAiNewsOutput | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const { toast } = useToast();

    const handleGenerateNews = async () => {
        setIsLoading(true);
        setNews(null);
        try {
            const result = await generateAiNews();
            setNews(result);
        } catch (error) {
            console.error("Failed to generate AI news:", error);
            toast({
                title: "Generation Failed",
                description: "Could not generate the news article. Please try again.",
                variant: "destructive",
            });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="h-full flex flex-col">
            <header className="border-b p-3 md:p-4 flex items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                    <SidebarTrigger className="md:hidden" />
                    <div>
                      <h1 className="text-lg md:text-xl font-bold">AI News</h1>
                      <p className="text-sm text-muted-foreground">
                          Get the latest updates from the world of AI.
                      </p>
                    </div>
                </div>
                <ThemeToggle />
            </header>
            <main className="flex-1 overflow-auto p-2 sm:p-4 md:p-6">
                <div className="max-w-4xl mx-auto space-y-6">
                    <Card className="text-center">
                        <CardHeader>
                            <CardTitle>Generate Real-Time AI News</CardTitle>
                            <CardDescription>
                                Click the button below to get a fresh news article about a recent development in AI, generated by our AI journalist.
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <Button onClick={handleGenerateNews} disabled={isLoading}>
                                {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
                                {isLoading ? 'Generating...' : 'Get Latest News'}
                            </Button>
                        </CardContent>
                    </Card>

                    {isLoading && (
                        <div className="flex justify-center items-center py-10">
                            <Loader2 className="w-10 h-10 animate-spin text-primary" />
                        </div>
                    )}

                    {news && (
                        <Card className="shadow-lg animate-in fade-in-50">
                            <CardHeader>
                                <div className="flex items-center gap-3">
                                    <Newspaper className="w-8 h-8 text-primary" />
                                    <CardTitle className="text-2xl md:text-3xl">{news.headline}</CardTitle>
                                </div>
                            </CardHeader>
                            <CardContent>
                                <div className="prose prose-sm sm:prose-base dark:prose-invert max-w-none text-foreground whitespace-pre-wrap">
                                    {news.article}
                                </div>
                            </CardContent>
                        </Card>
                    )}
                </div>
            </main>
        </div>
    );
}
